name: Test, Build and deploy

on:
  push:
  workflow_dispatch:

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          NODE_ENV: development
          CI: true

      - name: Run tests
        run: npm test

      - name: Build site
        run: npm run build

      - name: Add CNAME
        if: github.ref == 'refs/heads/master'
        run: echo "mattcowley.co.uk" > build/CNAME

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
          clean: true
          single-commit: true
